### PR TITLE
Add Cardinal specific changes

### PR DESCRIPTION
**Pull request by falkTX**
Hi there.

This PR adds the necessary changes to make the Terrorform `osdialog` usage work within [Cardinal](https://github.com/DISTRHO/Cardinal).
Since `osdialog` calls are blocking, Cardinal does not use it (it is in my opinion very bad practice for plugins to block the main event loop).

Changes to the code are made in a way that compatibility with regular Rack remains intact.
I tried to change things as little as possible, the part about `onLoadWAVCallback` was an odd one due to it expecting a blocking operation.
Hopefully all still makes sense in the end.
Let me know if you have any questions.

### CODE REVIEW

**Review by ValleyAudio — COMMENTED** [review]
Please add ```#include "osdialog.h"``` to line 2 of ```src/Terrorform/TerrorformWaveTableEditor.cpp```, otherwise you will get compilation errors.

**Comment by falkTX** [comment]
Just added it now, force-pushed so it remains 1 single commit.

Sorry didn't realize this little change was needed, it has been a long time since I built the official Rack. :sweat_smile:
